name: Release with artifact

on:
  workflow_dispatch:

jobs:
  package-linux-cross:
    name: Linux cross-compile builds
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    container: "debian:buster"
    strategy:
      matrix:
        include:
          - prefix: aarch64-linux-gnu
            npm_arch: arm64
            apt_arch: arm64

    env:
      AR: ${{ format('{0}-ar', matrix.prefix) }}
      AS: ${{ format('{0}-as', matrix.prefix) }}
      CC: ${{ format('{0}-gcc', matrix.prefix) }}
      CPP: ${{ format('{0}-cpp', matrix.prefix) }}
      CXX: ${{ format('{0}-g++', matrix.prefix) }}
      FC: ${{ format('{0}-gfortran', matrix.prefix) }}
      LD: ${{ format('{0}-ld', matrix.prefix) }}
      STRIP: ${{ format('{0}-strip', matrix.prefix) }}
      PKG_CONFIG_PATH: ${{ format('/usr/lib/{0}/pkgconfig', matrix.prefix) }}
      TARGET_ARCH: ${{ matrix.apt_arch }}
      npm_config_arch: ${{ matrix.npm_arch }}
      NODE_VERSION: v16.20.2
      # Not building from source results in an x86_64 argon2, as if
      # npm_config_arch is being ignored.
      npm_config_build_from_source: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.2"

      - name: Install cross-compiler and system dependencies
        run: |
          dpkg --add-architecture $TARGET_ARCH
          apt-get update && apt-get install -y --no-install-recommends \
            crossbuild-essential-$TARGET_ARCH \
            libx11-dev:$TARGET_ARCH \
            libx11-xcb-dev:$TARGET_ARCH \
            libxkbfile-dev:$TARGET_ARCH \
            libsecret-1-dev:$TARGET_ARCH \
            libkrb5-dev:$TARGET_ARCH \
            ca-certificates \
            curl wget rsync gettext-base git
            
      - name: Clone
        run: |
          git clone https://${{secrets.GITEE_USERNAME}}:${{secrets.GITEE_PASSWORD}}@gitee.com/its-not-too-late-breeze/code-server.git

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        id: download
        with:
          branch: ${{ github.ref }}
          workflow: build-artifact.yml
          workflow_conclusion: completed
          name: npm-package
          check_artifacts: false
          if_no_artifact_found: fail

      - name: Decompress npm package
        working-directory: ./code-server
        run: |
          mv ../package.tar.gz ./
          tar -xzf package.tar.gz

      - name: Build standalone release
        working-directory: ./code-server
        run: npm run release:standalone

      - name: Replace node with cross-compile equivalent
        working-directory: ./code-server
        run: |
          wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-${npm_config_arch}.tar.xz
          tar -xf node-${NODE_VERSION}-linux-${npm_config_arch}.tar.xz node-${NODE_VERSION}-linux-${npm_config_arch}/bin/node --strip-components=2
          mv ./node ./release-standalone/lib/node

      # NOTE@jsjoeio - we do this so we can strip out the v
      # i.e. v4.9.1 -> 4.9.1
      - name: Get and set VERSION
        working-directory: ./code-server
        run: |
          echo "VERSION=4.7.0" >> $GITHUB_ENV

      - name: Build packages with nfpm
        working-directory: ./code-server
        env:
          VERSION: ${{ env.VERSION }}
        run: npm run package ${npm_config_arch}

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          discussion_category_name: "📣 Announcements"
          files: ./code-server/release-packages/*
