name: Test download

on:
  workflow_dispatch:

jobs:
  reports:
    name: Report Test Coverages
    runs-on: ubuntu-latest

    steps:
      - name: Download test reports
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: ${{ github.ref }}
          workflow: build-artifact.yml
          workflow_conclusion: completed
          name: npm-package
          check_artifacts: false

      - name: Submit to CodeClimate
        run: |
          curl -LSs $CC_TEST_REPORTER_URL > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter sum-coverage -o - reports/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -
